#!/usr/bin/python2
#global variables
close_date_list = \
{
    "gmsversion":
    {
        "8.1_r2": "-",
        "8.1_r1": "2018/3/9",
        "8.0_r5": "-",
        "8.0_r4": "2018/3/9",
        "8.0_r3": "2018/1/13",
        "7.1_r9": "-",
        "7.1_r8": "2018/3/9",
        "7.1_r7": "2018/1/13",
        "7.0_r13": "-",
        "7.0_r12": "2018/3/9",
        "7.0_r11": "2018/1/13"
    },
    "gts":
    {
        "5.1_r2": "-",
        "5.1_r1": "2018/1/28",
        "5.0_r2": "2018/1/15"
    },
    "cts":
    {
        "8.1_r1": "-",
        "8.0_r5": "-",
        "8.0_r4": "2018/2/19",
        "7.1_r13": "-",
        "7.1_r12": "2018/2/19",
        "7.0_r17": "-",
        "7.0_r16":"2018/2/19"
    },
    "verifier":
    {
        "8.1_r1": "-",
        "8.0_r5": "-",
        "8.0_r4": "2018/2/19",
        "7.1_r13": "-",
        "7.1_r12": "2018/2/19",
        "7.0_r17": "-",
        "7.0_r16":"2018/2/19"
    },
    "vts":
    {
        "8.1_r2": "-",
        "8.1_r1": "2018/2/6",
        "8.0_r6": "-",
        "8.0_r5": "2018/2/6",
        "8.0_r4": "2018/1/5"
    }
}
essential_apps = ['com.google.android.partnersetup',
                  'com.google.android.setupwizard',
                  'com.google.android.onetimeinitializer',
                  'com.google.android.gsf.login',
                  'com.google.android.gsf',
                  'com.google.android.feedback',
                  'com.google.android.backuptransport',
                  'com.google.android.packageinstaller']
must_apps = ['com.android.chrome',
             'com.google.android.gms',
             'com.google.android.googlequicksearchbox',
             'com.google.android.apps.maps',
             'com.google.android.youtube',
             'com.android.vending',
             'com.google.android.apps.docs',
             'com.google.android.music',
             'com.google.android.videos',
             'com.google.android.talk',
             'com.google.android.apps.photos',
             'com.google.android.gm',
             'com.google.android.tts',
             'com.google.android.webview',
             'com.google.android.apps.tachyon']
client_id_list=[
'android-agold',
'android-acer',
'android-allview',
'android-along',
'android-asbisc',
'android-ascom',
'android-askey',
'android-atlas',
'android-qisda',
'android-bird',
'android-blu',
'android-bluebird',
'android-borqs',
'android-bullitt',
'android-caron',
'android-chiptrip',
'android-chinoe',
'android-ckt',
'android-coosea',
'android-clementoni',
'android-colorsmobile',
'android-condor',
'android-vexmobile',
'android-cze',
'android-dewav',
'android-digiland',
'android-dnelectronics',
'android-dl',
'android-doogee',
'android-doro',
'android-droi',
'android-eastaeon',
'android-ecs',
'android-emdoor',
'android-esight',
'android-evercoss',
'android-fairphone',
'android-fortuneship',
'android-fih',
'android-gmphone',
'android-getac',
'android-gigaset',
'android-gionee',
'android-gotron',
'android-gstone',
'android-haier',
'android-hena',
'android-hct',
'android-highscreen',
'android-himax',
'android-hipstreet',
'android-hotwav',
'android-huaqin',
'android-navon',
'android-hyst',
'android-itt',
'android-inet',
'android-infocus',
'android-infosonics',
'android-innovatech',
'android-mobicell',
'android-jet',
'android-joyar',
'android-k2konnect',
'android-ktouch',
'android-landis',
'android-lanix',
'android-leagoo',
'android-lephone',
'android-lexibook',
'android-logicom',
'android-longcheer',
'android-m4tel',
'android-masscom',
'android-datamatic',
'android-meitu',
'android-meizu',
'android-mobistar',
'android-mobiwire',
'android-motorolasolutions',
'android-multilaser',
'android-myphonepl',
'android-navcity',
'android-nec',
'android-ngmitalia',
'android-nlgsm',
'android-onkyo',
'android-panasonic',
'android-pcd',
'android-pegatron',
'android-pitney',
'android-plaisio',
'android-planetavvio',
'android-freetel',
'android-prestigio',
'android-proexpress',
'android-proscan',
'android-bbmerahputih',
'android-quanta',
'android-razer',
'android-alco',
'android-revoview',
'android-scadvanced',
'android-sanmu',
'android-sangfei',
'android-selvas',
'android-bopel',
'android-jeko',
'android-malata',
'android-sico',
'android-skydevices',
'android-skyworth',
'android-smd',
'android-auchan',
'android-socialmobile',
'android-sonimtech',
'android-southerntelecom',
'android-spectralink',
'android-sprocomm',
'android-starmobile',
'android-stk',
'android-suncupid',
'android-techain',
'android-teleepoch',
'android-sztem',
'android-topwise',
'android-tinno',
'android-toshiba',
'android-tplink',
'android-trimble',
'android-uniscope',
'android-usa111',
'android-vanzo',
'android-vestel',
'android-vsun',
'android-wheatek',
'android-walton',
'android-wiko',
'android-wind',
'android-wingtech',
'android-wistron',
'android-worldchip',
'android-xtr',
'android-efun',
'android-zebra',
'android-zechin',
'android-zound'
]

waiver_list=[
                {'module':'GtsBackupHostTestCases',
                 'test_case':'com.google.android.gts.backup.BackupPermissionRestrictionHostSideTest',
                 'test_item':'testOnlyWhitelistedTransportsOrPackagesHoldBackupPermission',
                 'suite_plan':'gts',
                 'suite_version':'5.1_r1',
                 'build_version':'7.0'},
                {'module':'GtsMediaTestCases',
                 'test_case':'com.google.android.media.gts.WidevineYouTubePerformanceTests',
                 'test_item':'testL3Cenc720P60',
                 'suite_plan':'gts',
                 'suite_version':'5.1_r1',
                 'build_version':'7.0'},
                {'module':'GtsMediaTestCases',
                 'test_case':'com.google.android.media.gts.WidevineYouTubePerformanceTests',
                 'test_item':'testClear720P60',
                 'suite_plan':'gts',
                 'suite_version':'5.1_r1',
                 'build_version':'7.0'}
            ]
